version: "3.8"

services:
 db:
  image: mysql:latest
  ports:
   - 3306
  environment:
   MYSQL_USER: student
   MYSQL_PASSWORD: 12345
  networks:
   - default
 app:
  image: img91
  ports:
   - 8080:8080
  environment:
   spring.datasource.url: jdbc:mysql://localhost:3306/student_managements
   spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
   spring.datasource.username: student
   spring.datasource.password: 12345
  depends_on:
   - db
  networks:
   - default
